version: "3.9"
services:
  dotnet.api:
    container_name: dotnet.api
    build:
      context: .
      dockerfile: ./AccountantOffice.Api/Dockerfile
    depends_on: 
      - db
  db:
    container_name: mssql.db
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "&R401!spC"
        ACCEPT_EULA: "Y"
    ports:
      - "1444:1433"
  front:
    container_name: front
    build: 
      context: ./accountant-office-frontend
      dockerfile: Dockerfile
    ports: 
      - '80:80'