version: "3.9"
services:
  db:
    container_name: sql.db
    image: "postgres"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: R401spC
      POSTGRES_DB: AccountantDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  migrations:
    container_name: migrations
    image: "flyway/flyway:7.14.0"
    depends_on:
      - db

  dotnet.api:
    container_name: dotnet.api
    build:
      context: ./accountant-office-backend
      dockerfile: ./AccountantOffice.Api/Dockerfile
    ports:
      - '5011:80'
    depends_on:
      - migrations

  front:
    container_name: front
    build: 
      context: ./accountant-office-frontend
      dockerfile: Dockerfile
    ports: 
      - '80:80'