version: "3.9"
services:
  db:
    container_name: sql.db
    image: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  flyway:
    container_name: flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db/${POSTGRES_DB}
      - FLYWAY_GROUP=false
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./database-configuration/sql:/flyway/sql
    depends_on:
      - db

  dotnet.api:
    container_name: dotnet.api
    build:
      context: ./accountant-office-backend/AccountantOffice
      dockerfile: ./AccountantOffice.Api/Dockerfile
    ports:
      - 5010:80
      - 5011:443
    environment:
      - ConnectionStrings__AccountantConnectionString=Server=db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - IdentityServerUrl=http://identity-server
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - $USERPROFILE\.aspnet\https:/https/
    depends_on:
      - flyway

  identity-server:
    container_name: identity-server
    build:
      context: ./accountant-office-backend/IdentityServer
      dockerfile: ./IdentityServer.Api/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ConnectionStrings__AccountantConnectionString=Server=db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - $USERPROFILE\.aspnet\https:/https/
    depends_on:
      - flyway

  front:
    container_name: front
    build: 
      context: ./accountant-office-frontend
      dockerfile: Dockerfile
    ports: 
      - 80:80