version: "3.9"
services:
  db:
    container_name: sql.db
    image: "postgres"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: R401spC
      POSTGRES_DB: AccountantDB
    ports:
     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  flyway:
    container_name: flyway
    environment:
      - FLYWAY_USER=dbuser
      - FLYWAY_PASSWORD=R401spC
      - FLYWAY_URL=jdbc:postgresql://db/AccountantDB
      - FLYWAY_GROUP=false
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./database-configuration/sql:/flyway/sql
    depends_on:
      - db

  dotnet.api:
    container_name: dotnet.api
    build:
      context: ./accountant-office-backend
      dockerfile: ./AccountantOffice.Api/Dockerfile
    ports:
      - 5011:80
    environment:
      - ConnectionStrings__AccountantConnectionString=Server=db;Port=5432;Database=AccountantDB;User Id=dbuser;Password=R401spC;
    depends_on:
      - flyway

  front:
    container_name: front
    build: 
      context: ./accountant-office-frontend
      dockerfile: Dockerfile
    ports: 
      - 80:80